NODE_IP = "192.168.56.110"
USER = "rabouziaS"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Master Node (Server)
  config.vm.define USER do |master|
    master.vm.hostname = USER
    master.vm.network "private_network", ip: NODE_IP

    master.vm.provider "virtualbox" do |vb|
      vb.name = USER
      vb.memory = "2048"
      vb.cpus = 2
    end
    
    master.vm.provision "shell", path: "scripts/install.sh"
  end
end
