MASTER_NODE_IP = "192.168.56.110"
WORKER_NODE_IP = "192.168.56.111"
MASTER_USER = "rabouziaS"
WORKER_USER = "rabouziaSW"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Master Node (Server)
  config.vm.define MASTER_USER do |master|
    master.vm.hostname = MASTER_USER
    master.vm.network "private_network", ip: MASTER_NODE_IP
    # master.vm.synced_folder "./confs", "/vagrant", type:"virtualbox"

    master.vm.provider "virtualbox" do |vb|
      vb.name = MASTER_USER
      vb.memory = "2048"
      vb.cpus = 2
    end
    
    master.vm.provision "shell", path: "scripts/install_k3s_master.sh"
  end

  # Worker Node (Agent)
  config.vm.define WORKER_USER do |worker|
    worker.vm.hostname = WORKER_USER
    worker.vm.network "private_network", ip: WORKER_NODE_IP
    # worker.vm.synced_folder "./confs", "/vagrant", type:"virtualbox"
    
    worker.vm.provider "virtualbox" do |vb|
      vb.name = WORKER_USER
      vb.memory = "2048"
      vb.cpus = 2
    end
    
    worker.vm.provision "shell", path: "scripts/install_k3s_worker.sh", args: [MASTER_NODE_IP]
  end
end
