Vagrant.configure("2") do |config|
  # Specify the base box (OS image)
  config.vm.box = "generic/alpine312"

  config.vm.define "rabouziaS" do |control|
    control.vm.hostname = "rabouziaS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", "rabouziaS"]
        v.memory = 1024
        v.cpu = 1
    end
    config.vm.provision :shell, :inline => SHELL 
      ...
    SHELL
    control.vm.provision "shell", path: REDACTED
  end

  config.vm.define "rabouziaSW" do |control|
    control.vm.hostname = "rabouziaSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "rabouziaSW"]
      v.memory = 1024
      v.cpu = 1
    end
    config.vm.provision "shell", inline: <<-SHELL
      ...
    SHELL
    control.vm.provision "shell", path: REDACTED
  end
end
