Vagrant.configure("2") do |config|
  # Specify the base box (OS image)
  config.vm.box = "generic/alpine312"

  config.vm.define "rabouziaS" do |control|
    control.vm.hostname = "rabouziaS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
        v.memory = "1024"
        v.cpus = "1"
        v.name = "rabouziaS"
    end
    config.vm.provision :shell, inline: <<-SHELL 
      echo "Hello World from Server"
    SHELL
  end

  config.vm.define "rabouziaSW" do |control|
    control.vm.hostname = "rabouziaSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.memory = "1024"
      v.cpus = "1"
      v.name = "rabouziaSW"
    end
    config.vm.provision "shell", inline: <<-SHELL
      echo "Hello World from Server Worker"
    SHELL
  end
end
